included:
  - DSGet
  - DSGetCore/Sources

excluded:
  - DSGet.xcodeproj
  - DSGetTests
  - DSGetWidgets

disabled_rules:
  - trailing_comma
  - todo

opt_in_rules:
  # -- Closures & returns --
  - closure_spacing
  - implicit_return

  # -- Collections --
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - last_where
  - sorted_first_last

  # -- Safety --
  - force_unwrapping
  - fatal_error_message
  - unowned_variable_capture
  - legacy_multiple

  # -- Code style --
  - modifier_order
  - toggle_bool
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - redundant_type_annotation
  - joined_default_parameter
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing

  # -- SwiftUI / UIKit --
  - private_action
  - private_outlet

  # -- Inheritance --
  - overridden_super_call
  - prohibited_super_call


  # -- Readability --
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - number_separator
  - file_name_no_space
  - return_value_from_void_function
  - static_over_final_class

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - i
    - vm

nesting:
  type_level: 2
  function_level: 3

cyclomatic_complexity:
  warning: 15
  error: 25

number_separator:
  minimum_length: 5

analyzer_rules:
  - unused_declaration
  - unused_import
