name: DSGet
options:
  bundleIdPrefix: es.ncrd
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages:
  DSGetCore:
    path: DSGetCore

targets:
  DSGet:
    type: application
    platform: iOS
    sources:
      - path: DSGet
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: DSGetCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: es.ncrd.DSGet
        INFOPLIST_FILE: DSGet/Info.plist
        CODE_SIGN_ENTITLEMENTS: DSGet/DSGet.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        ENABLE_PREVIEWS: true
    info:
      path: DSGet/Info.plist
      properties:
        CFBundleDisplayName: DSGet
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: DSGet/DSGet.entitlements
      properties:
        com.apple.security.application-groups:
          - group.es.ncrd.DSGet

  DSGetWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: DSGetWidgets
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: es.ncrd.DSGetWidgets
        INFOPLIST_FILE: DSGetWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: DSGetWidgets/DSGetWidgets.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        SKIP_INSTALL: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        ENABLE_PREVIEWS: true
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    info:
      path: DSGetWidgets/Info.plist
    entitlements:
      path: DSGetWidgets/DSGetWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.es.ncrd.DSGet
    dependencies:
      - target: DSGet
        embed: false

  iDSGet Watch App:
    type: application
    platform: watchOS
    deploymentTarget:
      watchOS: "11.0"
    sources:
      - path: iDSGet Watch App
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: es.ncrd.iDSGetWatchApp
        INFOPLIST_FILE: iDSGet Watch App/Info.plist
        CODE_SIGN_ENTITLEMENTS: iDSGet Watch App/iDSGet Watch App.entitlements
        TARGETED_DEVICE_FAMILY: "4"
        SKIP_INSTALL: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        ENABLE_PREVIEWS: true
    info:
      path: iDSGet Watch App/Info.plist
      properties:
        CFBundleDisplayName: iDSGet Watch
        WKApplicationNavigationBarTitleText: iDSGet Watch
        WKWatchKitExtension: ""
    entitlements:
      path: iDSGet Watch App/iDSGet Watch App.entitlements
      properties:
        com.apple.security.application-groups:
          - group.es.ncrd.DSGet
    dependencies:
      - target: DSGetCore

schemes:
  DSGet:
    build:
      targets:
        DSGet: all
        DSGetWidgets: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
